//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HefestoServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerts
    {
        public int Alert_Id { get; set; }
        public int Alert_Device { get; set; }
        public int Alert_Type { get; set; }
        public Nullable<int> Alert_Isread { get; set; }
        public System.DateTime Alert_Opendate { get; set; }
        public Nullable<System.DateTime> Alert_Closedate { get; set; }
    
        public virtual Alert_Types Alert_Types { get; set; }
        public virtual Device_Information Device_Information { get; set; }
    }
}
