//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HefestoServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Information
    {
        public Device_Information()
        {
            this.Alerts = new HashSet<Alerts>();
            this.Monitor = new HashSet<Monitor>();
        }
    
        public int Device_Id { get; set; }
        public string Device_Name { get; set; }
        public Nullable<double> Device_Lat { get; set; }
        public Nullable<double> DEvice_Long { get; set; }
        public string Device_Email { get; set; }
        public Nullable<int> Device_Mode { get; set; }
        public Nullable<int> Device_Status { get; set; }
        public string Device_Zone { get; set; }
        public Nullable<int> Device_SetPoint { get; set; }
        public Nullable<int> Device_Histerresys { get; set; }
        public Nullable<System.TimeSpan> Device_OnTime { get; set; }
        public Nullable<System.TimeSpan> Device_OffTime { get; set; }
        public Nullable<int> Device_Port_On_Over { get; set; }
        public Nullable<int> Device_Port_Off_Under { get; set; }
        public Nullable<int> Device_Port_In { get; set; }
    
        public virtual ICollection<Alerts> Alerts { get; set; }
        public virtual ICollection<Monitor> Monitor { get; set; }
    }
}
