//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HefestoServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int Monitor_Id { get; set; }
        public int Monitor_Device { get; set; }
        public System.DateTime Monitor_Date { get; set; }
        public Nullable<int> Monitor_Status { get; set; }
        public Nullable<double> Monitor_Current { get; set; }
        public Nullable<double> Monitor_Voltage { get; set; }
        public Nullable<double> Monitor_Var1 { get; set; }
        public Nullable<double> Monitor_Var2 { get; set; }
        public Nullable<double> Monitor_Temp { get; set; }
    
        public virtual Device_Information Device_Information { get; set; }
    }
}
